services:
    pictures_db:
        image: mysql:latest
        restart: always
        container_name: picturesDB
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - '3801:3306'

    pictures_web:
        image: node:hydrogen-slim
        container_name: pictures
        command: /bin/sh -c "cd /srv/app && npm install && npm run dev"
        ports:
            - 3800:3000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
